apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jenkins
  name: practice
  labels:
    app: practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: practice
  template:
    metadata:
      labels:
        app: practice
    spec:
      containers:
      - name: practice
        image: stibbsj/jenkinspractice
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-socket
      volumes:
        - name: docker-socket
          hostPath:
                path: /var/run/docker.sock
      restartPolicy: Always
