apiVersion: v1
kind: Service
metadata:
    name: jenkins-service
    namespace: jenkins
spec:
    type: NodePort
    selector:
        app: practice
    ports:
        - port: 8080
          name: jenkins
          targetPort: 8080
          nodePort: 30000